Fix reverse option
webcat12345/ngx-ui-switch pull request #488
Opened 2023-11-03 14:32 UTC by blazekv

I am not sure if this is best way how to fix it, but there were two main issues here.

On was that reverse option did not switch labels (which I fixed by setting CSS  class 'switch-label-checked' and 'switch-label-unchecked' based on reverse.

Second one was that in case of default behavior color and defaultBgColor was not set and therefore line 135
` return !this.checked ? this.color : this.defaultBgColor;` did not have effect (color was took from CSS).

2023-11-03 16:11 UTC, cmckni3 commented on src/lib/ui-switch/ui-switch.component.html
> -      class="switch-label-checked"
Maybe use a method with the logic?

2023-11-03 16:11 UTC, cmckni3 commented on src/lib/ui-switch/ui-switch.component.html
> -      class="switch-label-unchecked"
Maybe use a method with the logic?

2023-11-03 16:11 UTC, cmckni3 commented on src/lib/ui-switch/ui-switch.component.ts
> -    this.color = config && config.color;
Remove default

2023-11-03 16:11 UTC, cmckni3 commented on src/lib/ui-switch/ui-switch.component.ts
> -    this.defaultBgColor = config && config.defaultBgColor;
Remove default

2023-11-03 16:12 UTC, cmckni3 requested changes
See comments

2023-11-06 14:29 UTC, blazekv commented on src/lib/ui-switch/ui-switch.component.html
> -      class="switch-label-checked"
OK, i move it into method

2023-11-07 07:09 UTC, cmckni3 approved these changes

2023-11-07 07:09 UTC, merged

2023-11-07 07:09 UTC, cmckni3 commented
Thanks!